/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const UserProfile = t.iface([], {
  "email": "string",
  "loginEmail": t.opt("string"),
  "name": "string",
  "picture": t.opt(t.union("string", "null")),
  "anonymous": t.opt("boolean"),
  "connectId": t.opt(t.union("string", "null")),
  "loginMethod": t.opt(t.union(t.lit('Google'), t.lit('Email + Password'), t.lit('External'))),
  "locale": t.opt(t.union("string", "null")),
});

const exportedTypeSuite: t.ITypeSuite = {
  UserProfile,
};
export default exportedTypeSuite;
